DROP TABLE IF EXISTS transaccion;
DROP TABLE IF EXISTS categoria;
DROP TABLE IF EXISTS cuenta;

CREATE TABLE cuenta (id INT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(280) NOT NULL, inicial FLOAT NOT NULL, ingresos FLOAT, gastos FLOAT, total FLOAT);
CREATE TABLE transaccion (id INT PRIMARY KEY AUTO_INCREMENT, fecha DATETIME NOT NULL, descripcion VARCHAR(560) NOT NULL, importe FLOAT NOT NULL, categoria_id INT NOT NULL, tipo_id INT NOT NULL, cuenta_id INT NOT NULL);
CREATE TABLE categoria (id INT PRIMARY KEY AUTO_INCREMENT, descripcion VARCHAR(280) NOT NULL);

ALTER TABLE transaccion ADD FOREIGN KEY (cuenta_id) REFERENCES cuenta(id);
ALTER TABLE transaccion ADD FOREIGN KEY (categoria_id) REFERENCES categoria(id);